ergebnis/php-package-template

src/Example.php
test/Unit/ExampleTest.php

Fix: Add example to pass build

---

.gitattributes

Fix: Keep entries sorted in .gitattributes

---

phpstan.neon
src/Example.php

Enhancement: Configure phpstan to infer private property types from constructor

---

.travis.yml
Makefile

Fix: Validate composer.json and composer.lock with --strict option

---

.github/stale.yml
.github/workflows/stale.yml

This PR
💁‍♂ For reference, see https://github.com/actions/stale.

Enhancement: Use actions/stale instead of probot/stale

---

.dependabot/config.yml

This PR
💁‍♂ For reference, see https://dependabot.com/docs/config-file/#available-update-strategies.

Enhancement: Increase versions when updating dependencies

---

.github/workflows/ci.yml

Fix: Do not bother validating composer.json twice

---

.github/settings.yml

Enhancement: Reference ci.yml as required status check

---

.github/settings.yml

Fix: Use job names for required status checks

---

.github/workflows/continuous-integration.yml

Fix: Do not build Docker image when running mutation tests

---

.github/workflows/continuous-integration.yml

Enhancement: Explicitly specify token when sending code coverage to Codecov.io

---

.github/workflows/docker.yml

Fix: Reference

---

.github/workflows/continuous-integration.yml

Fix: Do not collect code coverage before running mutation tests

---

.github/settings.yml

Fix: Require codecov/patch and codecov/project to pass

---

README.md

This PR
💁‍♂ For reference, see https://help.github.com/en/articles/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository.

Fix: Badge

---

.php_cs

Fix: Do not bother ignoring non-existent directory

---

phpbench.json

Fix: Remove phpbench files

---

.github/workflows/continuous-integration.yml

Fix: Do not bother dumping Xdebug filter script for mutation tests

---

.github/workflows/continuous-integration.yml

Less noisy composer install steps

---

Makefile

Enhancement: Reduce noise from Makefile as well

---

.github/settings.yml

Enhancement: Use Octocat in repository description

---

.github/workflows/continuous-integration.yml

This PR
💁‍♂ For reference, see 
* https://github.com/sebastianbergmann/phpunit/pull/3833
* https://github.com/codecov/codecov-bash/pull/199

Fix: Do not fail step when sending code coverage failed

---

.github/workflows/continuous-integration.yml

This PR
So there are two strategies here,
1. Simple caching on the hash of `composer.lock`
2. Try to maintain a global cache used across all jobs, which will work when `composer.lock` is not committed.
Strategy number 2 is committed here.
You'll notice the deps are cached for for all combinations of the `tests` job.
cc @teohhanhui

GitHub Actions: cache composer dependencies

---

.github/workflows/continuous-integration.yml

This PR
💁‍♂ For reference, see https://github.com/actions/cache/issues/65.
Looks like you're right, @bendavies, this indeed works better.

Fix: Use commit hash to calculate cache key

---

.github/workflows/continuous-integration.yml

Fix: Use version for actions/checkout

---

.github/workflows/continuous-integration.yml

This PR
This makes the CI to run only once on new pull request.

Prevent CI to run twice on Pull Request

---

.github/workflows/continuous-integration.yml

This PR
Follows https://github.com/localheinz/php-library-template/pull/145#discussion_r344034156.

Fix: Remove redundant cache key

---

.github/workflows/continuous-integration.yml

Fix: Run php-cs-fixer with --dry-run option

---

README.md

Fix: Rename badge label

---

Makefile

Fix: Move phony target declaration to targets

---

.github/CONTRIBUTING.md
Makefile

This PR
💁‍♂ Personally, I only run
```
$ make
```
so I don't care much about the names of the targets. Renaming them brings them in line with the names of the jobs on GitHub actions, and also makes them a bit more independent from what tools we are using.

Fix: Rename targets

---

.github/CONTRIBUTING.md

Fix: Mention maglnet/composer-require-checker in CONTRIBUTING.md

---

.php_cs
CHANGELOG.md
README.md
composer.json
composer.lock
src/Example.php
test/AutoReview/SrcCodeTest.php
test/Unit/ExampleTest.php

Fix: Rename references and namespaces after move to ergebnis

---

Makefile

This PR
Thank you, @bendavies!

Fix: Simplify baseline regeneration

---

CHANGELOG.md

Fix: Remove non-applicable content from CHANGELOG.md

---

.github/workflows/continuous-integration.yml
Makefile

Fix: Run dependency analysis on PHP 7.4

---

.github/workflows/continuous-integration.yml

Fix: Use released versions of shivammathur/setup-php

---

.github/workflows/continuous-integration.yml

This PR
💁‍♂ Since several actions have released updates recently and I have never received any pull requests from Dependabot updating them, I think it’s safe to assume that the feature currently does not work as expected. By widening what appears to be a version constraint (still missing something similar to `^` and `~` operators, we will let GitHub figure it out).

Fix: Widen version constraint for GitHub actions

---

.github/workflows/continuous-integration.yml

This PR
💁‍♂ Might be necessary again when switching back to using PHP binaries available without using `shivammathur/setup-php`.

Fix: No need to use which

---

phpstan.neon

Fix: Do not include bleedingEdge.neon anymore

---

phpstan.neon

Fix: Remove non-applicable configuration

---

.github/workflows/continuous-integration.yml

Fix: Path to php-cs-fixer cache

---

composer.json
composer.lock
test/AutoReview/SrcCodeTest.php
test/Unit/ExampleTest.php

Enhancement: Use ergebnis/test-util instead of localheinz/test-util

---

.github/workflows/continuous-integration.yml

Fix: Do not use deprecated inputs

---

.github/CONTRIBUTING.md
.github/workflows/continuous-integration.yml
Makefile

Enhancement: Use pcov instead of Xdebug

---

.dependabot/config.yml

Fix: Remove dependabot configuration without effect

---

.github/workflows/continuous-integration.yml

This PR
💁‍♂ At the moment it is a bit unclear which version of an action is actually used, so using concrete version provides a bit more clarity. Also see https://github.community/t5/GitHub-Actions/Referencing-major-version-of-GitHub-action-only-fails-to/m-p/40562#M4280.

Fix: Use tags to specify versions of actions to be used

---

.github/workflows/continuous-integration.yml
Makefile

Enhancement: Use webfactory/composer-require-checker instead of localheinz/composer-require-checker-action

---

.dependabot/config.yml
.github/settings.yml

This PR
Follows #192.
Also see https://github.com/dependabot/feedback/issues/86.

Enhancement: Allow dependabot to automatically merge pull requests

---

.github/workflows/continuous-integration.yml

Fix: Use single line for single chache restore key

---

.github/settings.yml

Fix: Include hashes when specifying color codes

---

.github/settings.yml

Fix: Use empty descriptions

---

phpstan.neon

Fix: Do not bother checking iterable type

---

.github/workflows/continuous-integration.yml

This PR
💁‍♂ Not needed at this point!

Fix: Do not run builds for tags

---

.github/workflows/continuous-integration.yml

Fix: Actually use matrix

---

.github/workflows/approve.yml

Enhancement: Use different token

---

.github/CODEOWNERS
.github/workflows/continuous-integration.yml

This PR
💁‍♂ This is a temporary work-around until https://github.com/dependabot/feedback/issues/86#issuecomment-568274751 is resolved.

Fix: Remove CODEOWNERS

---

composer.json
composer.lock

Fix: Use caret operator for ergebnis/php-cs-fixer-config

---

.github/CODEOWNERS
.github/workflows/continuous-integration.yml

Fix: Use AUTO_APPROVE_TOKEN

---

.github/workflows/continuous-integration.yml
Makefile

Fix: Hide info level error messages emitted by vimeo/psalm

---

.dependabot/config.yml

This PR
💁‍♂ This only duplicates the [`CODEOWNERS`](https://github.com/ergebnis/php-library-template/blob/f1da331dc34b9edfc85c006c335812ef7872aa95/.github/CODEOWNERS) facilities, as far as I'm concerned.

Fix: Remove default_assignes and default_reviewers configuration

---

.github/settings.yml

Fix: Add note about restrictions

---

.github/FUNDING.yml

Fix: Remove Patreon from FUNDING.yml

---

.github/settings.yml

Fix: Do not require Approve job to pass

---

.github/settings.yml

This PR
Follows #270.
Follows #271. 
💁‍♂ Yes, it's named Review, not Approve.

Fix: Require Review job to pass

---

.github/workflows/continuous-integration.yml
README.md
infection.json

This PR
Follows #291.
💁‍♂ Missing support for platforms other than Travis CI (see https://github.com/infection/infection/pull/939).

Fix: Remove mutation score badge

---

.github/settings.yml

This PR
Reverts #210.
https://developer.github.com/v3/issues/labels/#create-a-label clearly states that it doesn't supports it.

Remove leading `#` of color labels

---

.github/workflows/continuous-integration.yml

This PR
💁‍♂ For reference, see https://medium.com/@ondrejmirtes/from-minutes-to-seconds-massive-performance-gains-in-phpstan-163be88d1519.

Enhancement: Cache cache directory for phpstan/phpstan

---

README.md

Fix: Reference master branch

---

.github/workflows/renew.yml

Fix: Renew workflow should run on PHP 7.2

---

.github/workflows/integrate.yml

This PR
💁‍♂ In a different project we ran into some issues - static code analysis failed, likely due to caching issues. These issues might have been resolved in the meanwhile, but better safe than sorry.

Fix: Do not cache cache directory for phpstan/phpstan

---

Makefile

Fix: Create directory for phpunit cache result file

---

phpstan.neon

Fix: Make it more obvious that we are dealing with directories

---

.editorconfig

This PR
Follows #338 
We still have `.github/settings.yml`.

Fix: support yml and yaml extension file in editor config

---

.github/workflows/integrate.yaml

This PR
These caches are immutable, but need to be updated when code changes.
We need to have a changing cache key for that to happen.

fix caching phpstan and psalm caches

---

.github/workflows/integrate.yaml

This PR
I seem to remember the `**/` used to be required, but not any more.

Simplify hashFiles for composer.lock files

---

.yamllint.yaml

Fix: Do not check multi-line strings for indentation

---

.github/settings.yml

Fix: Remove dependabot from restriction exclusions

---

.github/CODEOWNERS

Fix: CODEOWNERS

---

.github/CONTRIBUTING.md
Makefile

This PR
💁‍♂ It's slow, and that's annoying.

Fix: Exclude dependency-analysis from it target

---

.gitignore
.php_cs
.yamllint.yaml

This PR
Related to https://localheinz.com/blog/2019/10/25/project-notes/.

Fix: Ignore .notes directory

---

phpstan.neon

Fix: Remove placeholder

---

.github/CONTRIBUTING.md

Fix: Add note about yamllint to CONTRIBUTING.md

---

.yamllint.yaml

Fix: Consistently quote strings in YAML files

---

.github/workflows/triage.yaml

Enhancement: Add label based on branch name

---

.github/settings.yml

Fix: Require label job to pass

---

.github/settings.yml

Fix: Keep required jobs sorted by name

---

.github/CONTRIBUTING.md
Makefile

Enhancement: Normalize composer.json in coding-standards target

---

.php_cs
test/Unit/ExampleTest.php

Fix: Import parent namespace only

---

.github/workflows/triage.yaml

This PR
For reference, see https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onevent_nametypes and https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request.

Enhancement: Use event types instead of custom if

---

.gitattributes
.php_cs

Fix: Remove reference to previously removed directory

---

.github/settings.yml

This PR
💁‍♂️ It only runs when a pull request is opened, but not when it is pushed into.

Fix: Do not require Label job to pass

---

.github/workflows/integrate.yaml
.github/workflows/prune.yaml
.github/workflows/renew.yaml
.github/workflows/triage.yaml

Fix: Use major.minor.patch versions for GitHub actions

---

psalm.xml

This PR
💁‍♂️ For reference, see https://psalm.dev/docs/running_psalm/configuration/.

Enhancement: Configure psalm to detect unused variables and parameters

---

psalm.xml

This PR
💁‍♂️ For reference, see https://psalm.dev/docs/running_psalm/configuration/.

Enhancement: Configure psalm to enforce strict typing on numerical and string operations

---

.github/workflows/triage.yaml

This PR
💁‍♂️ For reference, see https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/.

Enhancement: Run triage workflow on pull_request_target event

---

.github/workflows/prune.yaml

Fix: Consider issues as stale when they are older than 180 days

---

.github/actions/composer/composer/install/run.sh

This PR
💁‍♂️ Otherwise steps succeed when they should have failed.

Fix: Exit with exit code from running composer

---

.github/workflows/integrate.yaml
.github/workflows/renew.yaml

The cache key for php-cs-fixer needs to be changing with the source code, so the cache is updated.
This is the same method used in the static analysis tools.

Correct the cache key for php-cs-fixer

---

.github/actions/composer/composer/determine-cache-directory/action.yaml

This PR
💁‍♂️ For reference, see https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/.

Fix: Echo COMPOSER_CACHE_DIR environment variable into $GITHUB_ENV instead of using set-env

---

.github/workflows/integrate.yaml

Fix: Dump coverage logs into different directory

---

.php_cs

This PR
💁‍♂️ The order does not matter, so we can just as well use alphabetical order.

Fix: Order

---

.github/workflows/integrate.yaml
Makefile

This PR
💁‍♂️ Despite being advertised (see https://github.com/vimeo/psalm/commit/fd43ba7a35975441b76d2f6481401d2daed26b5e), it has been removed in `vimeo/psalm:^4.0.0`.

Fix: Remove --diff-methods option

---

.github/workflows/integrate.yaml

Fix: Use major.minor.patch version

---

.github/actions/composer/composer/install/run.sh
Makefile

Fix: Remove deprecated --no-suggest option

---

.github/dependabot.yaml

Fix: Let dependabot update only once a week

---

.github/dependabot.yaml

This PR
💁‍♂️ For reference, see https://twitter.com/localheinz/status/1337825636396756992.

Fix: Reduce dependabot pull request limit from 10 to 1

---

.github/dependabot.yaml

This PR
Reverts #603.
Follows #604.
💁‍♂️ With #604 in place, I'm afraid it will be impossible to keep up-to-date in repositories depending on, for example, a range of `symfony/*` components.

Fix: Let dependabot update once a day

---

.github/settings.yml
.github/workflows/integrate.yaml
.github/workflows/renew.yaml
.php_cs
composer.json
composer.lock

This PR
💁‍♂️ Official support for PHP 7.2 ended on November 30, 2020. For reference, see 
- https://www.php.net/supported-versions.php
- https://www.php.net/eol.php

Fix: Drop support for PHP 7.2

---

.github/settings.yml
.github/workflows/integrate.yaml

This PR
❗ Blocked by https://github.com/ergebnis/php-library-template/pull/621.

Enhancement: Run mutation tests on PHP 8.0

---

.github/dependabot.yaml

Fix: Raise limit from 1 to 10

---

README.md

Fix: Remove branch query parameter

---

.github/workflows/renew.yaml

Fix: Do not run with --dry-run option

---

.github/workflows/integrate.yaml
.github/workflows/renew.yaml

Fix: Commit update of license year directly into default branch

---

.github/PULL_REQUEST_TEMPLATE.md

Fix: Avoid acronym

---

.github/workflows/integrate.yaml

💁‍♂️ It's more precise, and not as slow anymore.

Fix: Use Xdebug instead of pcov for collecting code coverage

---

.github/workflows/integrate.yaml
Makefile

Fix: Remove analyse or analyze argument when running phpstan

---

.gitattributes

It's pointless to include it in the source archives, it's there only to have a reproducible dev environment.

Fix: ignore composer.lock file when exporting the sources

---

.gitattributes
.github/workflows/integrate.yaml
.github/workflows/renew.yaml
.php-cs-fixer.php
Makefile

Fix: Rename .php_cs to .php-cs-fixer.php

---

.github/settings.yml
.php-cs-fixer.php
CHANGELOG.md
README.md
composer.json
composer.lock
src/Example.php
test/AutoReview/SrcCodeTest.php
test/Unit/ExampleTest.php

💁‍♂️ I believe package is a more common term.

Fix: Rename repository

---

.github/settings.yml

Fix: Remove merge label

---

.github/workflows/integrate.yaml

Enhancement: Use `github` output format when running `vimeo/psalm` on GitHub actions

---

.github/workflows/integrate.yaml

Fix: Do not use `github` output format when running `vimeo/psalm` on GitHub actions

---

.github/workflows/renew.yaml

Fix: Use PHP 7.4 for renew workflow

---

.github/workflows/integrate.yaml
Makefile

Fix: Do not cache cache directories for phpstan/phpstan and vimeo/psalm

---

phpstan-baseline.neon
test/Unit/ExampleTest.php
test/Util/Helper.php

Enhancement: Pull in `Helper` from `ergebnis/test-util`

---

.github/actions/composer/composer/install/run.sh

Enhancement: Use `--ansi` option

---

composer.json

💁‍♂️ For reference, see https://getcomposer.org/doc/06-config.md#allow-plugins.

Fix: Allow `ergebnis/composer-normalize` to run as `composer` plugin

---

.github/workflows/integrate.yaml
Makefile

Fix: Do not use `--diff` option

---

Makefile

Follows https://github.com/ergebnis/php-package-template/pull/844#issuecomment-1002810041.

Fix: Use `--allow-empty-baseline` option

---

.github/workflows/integrate.yaml

Fix: Enable `curl` extension

---

.editorconfig

Fix: Configure indentation for `*.md` files

---

.github/workflows/release.yaml

Fix: Do not use expressions to access environment variables

---

.github/workflows/integrate.yaml

Fix: Enable `pcntl` and `posix` extensions for static code analysis

---

.github/workflows/integrate.yaml

Enhancement: Use github output format

---

.github/settings.yml

💁‍♂️ For reference, see https://docs.github.com/en/rest/reference/branches#update-branch-protection--parameters.

Fix: Do not use deprecated `contexts` key

---

.github/workflows/integrate.yaml

💁‍♂️ For reference, see https://docs.codecov.com/docs/about-the-codecov-bash-uploader.

Fix: Use `codecov/codecov-action` to report coverage to `codecov.io`

---

.php-cs-fixer.php

Follows https://github.com/php/web-php/pull/559#discussion_r917249121.

Fix: Use `__FILE__` constant

---

.php-cs-fixer.php

Fix: Use file name, not path to file

---

.editorconfig

Add the sixth standard variable to EC: `end_of_line`
https://spec.editorconfig.org/#supported-pairs

Add `end_of_line` to `.editorconfig`

---

composer.json
composer.lock

Follows https://github.com/composer/composer/pull/11639.

Enhancement: Report abandoned packages when running `composer audit`

---

.github/dependabot.yaml

Fix: Allow updates of development dependencies only
