.dependabot/config.yml
.gitattributes
.php_cs

This PR
💁‍♂ For reference, see https://dependabot.com/docs/config-file/.

Enhancement: Add configuration for dependabot

---

.github/settings.yml

Enhancement: Add configuration for branch protection

---

.dependabot/config.yml
.github/settings.yml
.github/stale.yml

Enhancement: Add links to configuration documentation

---

.github/stale.yml

Enhancement: Sort keys

---

.github/settings.yml

Fix: Disable pages and projects

---

.github/settings.yml

Fix: Restrictions

---

.github/settings.yml
.php_cs
README.md
composer.json
src/Example.php
test/AutoReview/SrcCodeTest.php
test/Unit/ExampleTest.php

Enhancement: Prepare renaming of repository

---

composer.json
composer.lock

Fix: Package name

---

CHANGELOG.md

Fix: Links in CHANGELOG.md

---

.github/CONTRIBUTING.md
Makefile

Enhancement: Add help target to Makefile

---

Makefile

Fix: Keep targets in order

---

.github/actions/php-7.2/Dockerfile
.github/workflows/ci.yml
.travis.yml

Enhancement: Run php-cs-fixer using GitHub actions

---

.github/workflows/ci.yml
.travis.yml

Enhancement: Run composer-normalize using GitHub actions

---

.github/actions/php-7.2/Dockerfile

Fix: Run 'apt-get-clean'

---

.github/workflows/ci.yml

Fix: Rename job

---

.github/actions/php-7.2/Dockerfile

Fix: Install zip

---

.github/workflows/ci.yml
.travis.yml

Enhancement: Run 'composer validate' using GitHub actions

---

README.md

This PR
💁‍♂ For reference, see https://help.github.com/en/articles/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository.

Enhancement: Add GitHub actions status badge

---

.github/actions/php-7.3/Dockerfile
.github/workflows/ci.yml
.travis.yml

Enhancement: Run phpstan using GitHub actions

---

.github/workflows/ci.yml
.travis.yml

Enhancement: Run phpunit using GitHub actions

---

.docker/php-7.3-with-xdebug/Dockerfile
.github/settings.yml
.github/workflows/ci.yml
.travis.yml

Enhancement: Collect coverage using GitHub actions

---

composer.json
composer.lock

Enhancement: Configure platform to PHP 7.2.18

---

.github/settings.yml
.github/workflows/continuous-integration.yml

Enhancement: Use matrix strategy with if expressions to reduce repetition

---

.github/workflows/continuous-integration.yml

Fix: Point out that we are installing locked dependencies

---

.github/workflows/continuous-integration.yml
.github/workflows/docker.yml

Enhancement: Build, tag, and push Docker images on push to master

---

.github/workflows/continuous-integration.yml

Fix: Consistently use quotes for names

---

.gitattributes
.github/CONTRIBUTING.md
Makefile
composer.json
composer.lock

Fix: Remove phpbench/phpbench

---

.github/workflows/continuous-integration.yml

Fix: Reword

---

.github/workflows/continuous-integration.yml
Makefile

Fix: Use unified diff

---

.github/FUNDING.yml

Enhancement: Add link to buymeacoffee.com

---

.github/workflows/continuous-integration.yml

Fix: Keep options sorted

---

.github/workflows/continuous-integration.yml

Enhancement: Do not hard-code path to composer

---

.github/workflows/stale.yml

Fix: Add extra empty line

---

.github/workflows/continuous-integration.yml

Enhancement: Run static analysis on PHP 7.3

---

.github/settings.yml

Enhancement: Add security label

---

.github/settings.yml

Enhancement: Add question label

---

.github/CONTRIBUTING.md

Enhancement: Add section heading

---

.github/workflows/continuous-integration.yml

Disable xdebug

---

.github/workflows/continuous-integration.yml

Fix: Combine steps related to uploading code coverage

---

.dependabot/config.yml

This PR
💁‍♂ For reference, see
- https://github.com/localheinz/php-library-template/pull/132#discussion_r343548273
- https://github.com/dependabot/dependabot-core/tree/master/github_actions

Enhancement: Let dependabot update GitHub actions

---

.dependabot/config.yml

Fix: Configuration for dependabot

---

.github/settings.yml
composer.json

Enhancement: Mention GitHub actions in description

---

.dependabot/config.yml

Fixes #140.
Follows #136 and #139.

Fix: Configuration for dependabot again

---

.github/workflows/continuous-integration.yml

This PR
Follows #131, #135.
💁‍♂ For reference, see https://github.com/actions/cache/issues/65.

Fix: Cache issues

---

.github/settings.yml

Fix: Remove extra space

---

.github/workflows/continuous-integration.yml

Enhancement: Cache cache file for friendsofphp/php-cs-fixer

---

composer.json
composer.lock

Fix: Remove platform override

---

.github/settings.yml
.github/workflows/continuous-integration.yml
Makefile

Enhancement: Run maglnet/composer-require-checker

---

Makefile

Fix: Descriptions

---

.dependabot/config.yml

Fix: Update dependencies weekly

---

Makefile

Fix: Dependency

---

README.md

Fix: Label

---

.github/workflows/continuous-integration.yml

This PR
💁‍♂ For reference, see https://github.com/actions/cache/compare/v1.0.0...v1.0.2.

Fix: Update actions/cache

---

.dependabot/config.yml
.github/settings.yml

Enhancement: Configure labels for Dependabot pull requests

---

.github/CONTRIBUTING.md
Makefile
phpstan-baseline.neon
phpstan.neon

Enhancement: Make use of phpstan baseline feature

---

.github/workflows/stale.yml

Fix: Run stale job at 12pm only

---

.dependabot/config.yml

Enhancement: Automatically merge update of development dependency

---

.dependabot/config.yml

Fix: Go back to updating dependencies at least daily

---

.github/settings.yml
.github/workflows/continuous-integration.yml

Enhancement: Use matrix strategy to reduce repetition

---

.github/workflows/continuous-integration.yml
Makefile

This PR
💁‍♂ For reference, see https://github.com/localheinz/composer-require-checker-action/compare/1.1.0...1.1.1.

Fix: Update localheinz/composer-require-checker-action

---

composer.json
composer.lock
phpstan.neon

Enhancement: Require phpstan/extension-installer

---

composer.json
composer.lock

Bump infection/infection from 0.14.2 to 0.15.0

---

.github/workflows/continuous-integration.yml

This PR
💁‍♂ For reference, see https://github.com/actions/checkout/compare/v1.0.0...v2.0.0.

Enhancement: Use actions/checkout@v2.0.0

---

.dependabot/config.yml

Fix: Go back to updating dependencies live

---

.github/workflows/continuous-integration.yml

This PR
💁‍♂ For reference, see https://github.com/shivammathur/setup-php/compare/1.6.0...1.6.1.

Fix: Update shivammathur/setup-php

---

.github/workflows/continuous-integration.yml

Fix: Step name

---

.github/settings.yml
.github/workflows/continuous-integration.yml

Enhancement: Reduce repetition even more

---

.github/workflows/continuous-integration.yml

Enhancement: Extract environment variable REQUIRED_PHP_EXTENSIONS

---

.github/FUNDING.yml
.github/settings.yml
.github/workflows/continuous-integration.yml
.github/workflows/stale.yml

Fix: Consistently quote strings

---

.github/settings.yml

Fix: Restriction

---

.github/settings.yml

Enhancement: Configure repository topics

---

.github/workflows/continuous-integration.yml
Makefile

This PR
💁‍♂ This will make synchronization even easier.

Enhancement: Extract environment variables MIN_COVERED_MSI and MIN_MSI

---

.github/workflows/continuous-integration.yml

Fix: Use consistent spacing

---

.github/workflows/stale.yml

This PR
💁‍♂ For reference, see https://github.com/actions/stale/compare/1.0.0...v1.1.0.

Enhancement: Update actions/stale

---

.github/workflows/continuous-integration.yml
.github/workflows/stale.yml

Fix: Order

---

.github/workflows/continuous-deployment.yml
README.md

Enhancement: Automatically create release on tag

---

.github/workflows/continuous-deployment.yml

This PR
Follows #220.
💁‍♂ This ensure we have the tag available without leading `refs/tags`.
Also see https://github.com/actions/create-release/blob/v1.0.0/src/create-release.js#L13.

Enhancement: Determine raw tag

---

.github/workflows/continuous-integration.yml

This PR
💁‍♂ For reference, see https://github.com/shivammathur/setup-php/compare/1.6.2...1.7.0.

Enhancement: Update shivammathur/setup-php

---

.gitattributes
.github/CONTRIBUTING.md
.github/workflows/continuous-integration.yml
Makefile
composer.json
composer.lock
phpstan-baseline.neon
psalm-baseline.xml
psalm.xml

Enhancement: Use vimeo/psalm in addition to phpstan/phpstan

---

.dependabot/config.yml
.github/workflows/approve.yml

This PR
💁‍♂ Possibly a workaround for https://github.com/dependabot/feedback/issues/86#issuecomment-568274751.

Enhancement: Automatically approve pull requests updating development dependencies

---

composer.json
composer.lock

This PR
Related to #225.
💁‍♂ For reference, see https://github.com/ergebnis/php-cs-fixer-config/compare/1.0.0...1.1.0.

Enhancement: Update ergebnis/php-cs-fixer-config

---

composer.json
composer.lock

This PR
Related to #158. 
Reverts #151.

Fix: Configure platform

---

.github/workflows/continuous-integration.yml
README.md

Enhancement: Add badge for type coverage

---

.github/workflows/continuous-integration.yml
Makefile

Enhancement: Show statistics when running vimeo/psalm

---

.dependabot/config.yml
.github/settings.yml
.github/workflows/continuous-deployment.yml
.github/workflows/continuous-integration.yml

Enhancement: Let @ergebnis-bot approve pull requests and create releases

---

.github/workflows/stale.yml

Enhancement: Let @ergebnis-bot close stale issues

---

.github/CODEOWNERS

Enhancement: Add @ergebnis-bot to CODEOWNERS

---

.github/settings.yml

Enhancement: Add archived setting

---

.github/PULL_REQUEST_TEMPLATE.md

Fix: Reduce number of items in list

---

.github/settings.yml

This PR
❗️ Blocked by https://github.com/octokit/rest.js/issues/1543.

Enhancement: Delete branches on merge

---

.github/settings.yml

Fix: Require Approve job to pass

---

README.md

Fix: Give badges a break

---

.github/workflows/continuous-integration.yml

Enhancement: Approve pull requests by @ergebnis-bot updating the license year

---

.github/settings.yml

Fix: Do not require Review job to pass

---

.github/workflows/stale.yml

Fix: Wording

---

psalm.xml

Configure psalm's cache directory

---

.github/workflows/continuous-integration.yml
README.md
infection.json

This PR
Fixes #290.
💁‍♂ Thank you for the inspiration, @Lctrs!

Enhancement: Add mutation score badge

---

.github/workflows/continuous-integration.yml
.github/workflows/license.yml

Bump actions/cache from 1.0.3 to 1.1.2

---

.github/workflows/continuous-integration.yml
Makefile

This PR
💁‍♂ For reference, see https://github.com/maglnet/ComposerRequireChecker/compare/2.0.0...2.1.0.

Enhancement: Update maglnet/composer-require-checker

---

.github/workflows/stale.yml

This PR
💁‍♂ For reference, see https://yaml-multiline.info.

Fix: Keep new lines in stale messages

---

psalm.xml

This PR
For reference, see https://psalm.dev/docs/running_psalm/configuration/#errorLevel

Configure psalm error level

---

.github/workflows/continuous-integration.yml
.github/workflows/license.yml

This PR
💁‍♂ For reference, see https://github.com/shivammathur/setup-php#cache-composer-dependencies.

Enhancement: Determine composer cache directory

---

.php_cs
phpstan.neon
psalm.xml
test/AutoReview/SrcCodeTest.php
test/Unit/phpunit.xml

Fix: Make it more obvious that we are dealing with directories

---

.github/workflows/continuous-integration.yml

while reading the template its not standing out what the actual differences between the dependency modes are.
I tried to change the name of the steps a bit to make it more clear.

make comments more explicit

---

.github/workflows/continuous-integration.yml
.github/workflows/license.yml

Fix: Apply @staabm's patch everywhere

---

.github/workflows/continuous-deployment.yml
.github/workflows/continuous-integration.yml
.github/workflows/license.yml
.github/workflows/stale.yml

This PR
💁‍♂ Unsure about that one, to be honest.

Enhancement: Reference rolling tags where available

---

.github/CONTRIBUTING.md
.github/workflows/integrate.yml
.github/workflows/prune.yml
.github/workflows/release.yml
.github/workflows/renew.yml
README.md

Enhancement: Rename workflows

---

.github/workflows/prune.yml

Fix: Workflow name

---

.github/CONTRIBUTING.md

Fix: List workflows in CONTRIBUTING.md

---

README.md

Fix: Reorder and add missing badges

---

.github/workflows/integrate.yaml
.github/workflows/prune.yaml
.github/workflows/release.yaml
.github/workflows/renew.yaml
.yamllint.yaml
Makefile

Enhancement: Lint YAML files

---

.github/workflows/renew.yaml

This PR
💁‍♂ For reference, see https://github.com/gr2m/create-or-update-pull-request-action/compare/v1.2.9...v1.2.10.

Fix: Update gr2m/create-or-update-pull-request-action

---

.github/workflows/integrate.yaml

Cache cache directory for vimeo/psalm

---

.github/workflows/integrate.yaml
Makefile

speed up vimeo/psalm

---

.dependabot/config.yaml
.github/CODEOWNERS
.github/workflows/integrate.yaml

Enhancement: Let @ergebnis-bot review, approve, and merge pull requests

---

.github/workflows/integrate.yaml

Fix: Merge method

---

.github/CODEOWNERS

Fix: Add @ergebnis-bot to CODEOWNERS

---

.github/workflows/integrate.yaml

Fix: Actor is dependabot-preview[bot]

---

.github/settings.yml
.github/workflows/integrate.yaml

Enhancement: Let @ergebnis-bot merge pull request when it has merge label

---

.github/settings.yml
.github/workflows/integrate.yaml

Fix: Merge jobs

---

.github/workflows/integrate.yaml

Fix: Use multiple lines for condition

---

.github/workflows/integrate.yaml

Fix: Request review first

---

.github/workflows/integrate.yaml

Fix: Approve pull request only on selected actions

---

.github/CONTRIBUTING.md

Fix: Update CONTRIBUTING.md

---

.github/workflows/integrate.yaml

Fix: Stop waiting

---

Makefile

Fix: Description

---

README.md

Enhancement: Add link to list

---

infection.json

Fix: Sort items

---

.github/workflows/integrate.yaml
.github/workflows/triage.yaml

This PR
💁‍♂️ For reference, see https://github.com/actions/github-script/compare/0.8.0...v1.1.0.

Enhancement: Update actions/github-script

---

.github/workflows/integrate.yaml
.github/workflows/renew.yaml

This PR
💁‍♂️ For reference, see https://github.com/actions/cache/compare/v1.2.0...v2.0.0.

Enhancement: Update actions/cache

---

.github/CONTRIBUTING.md
README.md

Enhancement: Enable syntax highlighting

---

.github/dependabot.yml

Fix: Remove fragment

---

.github/dependabot.yml
.github/workflows/integrate.yaml

Enhancement: Automatically merge updates to GitHub Actions

---

.github/dependabot.yml

Fix: Restore versioning strategy configuration

---

.github/workflows/integrate.yaml
.github/workflows/renew.yaml

Fix: Rename environment variable

---

.github/dependabot.yml
.github/settings.yml
.github/workflows/integrate.yaml
.github/workflows/prune.yaml
.github/workflows/release.yaml
.github/workflows/renew.yaml
.github/workflows/triage.yaml

Fix: Update links to GitHub documentation

---

.github/FUNDING.yml

Enhancement: Synchronize with ergebnis/.github

---

.github/workflows/integrate.yaml

This PR
💁‍♂️ For reference, see https://github.com/shivammathur/setup-php#problem-matchers.

Enhancement: Set up problem matchers for phpunit/phpunit

---

.github/workflows/prune.yaml

Enhancement: Extract environment variables

---

.github/workflows/prune.yaml

Fix: Close stale issues after 14 days

---

.github/workflows/integrate.yaml

Fix: Rename variable

---

.github/workflows/integrate.yaml
.github/workflows/renew.yaml

Enhancement: Extract environment variables for @ergebnis-bot name and email where possible

---

.github/workflows/integrate.yaml
Makefile

Enhancement: Set memory limit to -1 when running phpstan

---

composer-require-checker.json

Fix: Indentation

---

.github/settings.yml
.github/workflows/integrate.yaml
composer.json
composer.lock

Enhancement: Add support for PHP 8.0

---

test/AutoReview/SrcCodeTest.php

Fix: Import

---

phpstan.neon

Fix: Add vertical whitespace

---

composer.json
composer.lock

Enhancement: Configure ergebnis/composer-normalize via composer extra

---

psalm.xml

Fix: Remove configuration

---

.github/PULL_REQUEST_TEMPLATE.md

This PR
💁‍♂️ For reference, see https://github.blog/changelog/2020-12-15-markdown-list-syntax-now-autocompleted/.

Fix: Remove check box

---

.github/settings.yml
.github/workflows/integrate.yaml

Enhancement: Collect code coverage on PHP 8.0

---

.github/settings.yml
.github/workflows/integrate.yaml

Enhancement: Run static code analysis on PHP 8.0

---

.github/workflows/integrate.yaml
Makefile
infection.json

Enhancement: Use configuration file for infection/infection

---

.github/workflows/integrate.yaml
.github/workflows/renew.yaml

Fix: Try to renew the license every hour on January 1st

---

.github/workflows/integrate.yaml
.github/workflows/renew.yaml

Fix: Inline environment variables

---

.github/workflows/renew.yaml

Fix: Schedule

---

.github/settings.yml
.github/workflows/integrate.yaml

Fix: Run jobs on lowest supported PHP version

---

.github/CONTRIBUTING.md

Fix: Reference

---

.github/CONTRIBUTING.md

Fix: Remove extra empty line

---

.github/workflows/integrate.yaml
.github/workflows/renew.yaml
Makefile

Fix: Remove --diff-format option

---

.github/workflows/integrate.yaml

Fix: Run workflow on pull_request_target

---

.github/workflows/merge.yaml

Fix: Remove extra parentheses

---

.github/workflows/merge.yaml
.github/workflows/triage.yaml

Fix: Update usage of octokit

---

.github/CONTRIBUTING.md
README.md

Follows https://github.com/ergebnis/composer-normalize/pull/803.

Fix: Allow users to copy shell commands

---

.github/actions/composer/composer/install/run.sh

Remove stray quotes

---

src/Example.php

Fix: Add property type declaration

---

.github/workflows/integrate.yaml
.github/workflows/renew.yaml

Enhancement: Use `--ansi` option

---

.github/PULL_REQUEST_TEMPLATE.md

Fix: Add trailing space

---

.github/workflows/integrate.yaml
.github/workflows/renew.yaml

Follows https://github.com/genkgo/camt/pull/112/files#r781308054.
💁‍♂️ For reference, see https://github.com/shivammathur/setup-php#php.

Enhancement: Set up problem matches for PHP

---

.github/workflows/release.yaml

Enhancement: Use environment variable

---

.github/workflows/release.yaml

💁‍♂️ For reference, see https://octokit.github.io/rest.js/v18#repos-generate-release-notes.

Enhancement: Automatically generate release body

---

.github/workflows/merge.yaml
.github/workflows/release.yaml
.github/workflows/triage.yaml

Fix: Consistently use semicolons and trailing commas

---

.github/workflows/merge.yaml
.github/workflows/release.yaml
.github/workflows/triage.yaml

Fix: Try and catch errors

---

.github/workflows/triage.yaml

Fix: Return early

---

.github/workflows/merge.yaml
.github/workflows/release.yaml
.github/workflows/triage.yaml

Fix: Inline constants

---

.github/workflows/release.yaml

Fix: Simplify

---

.github/workflows/merge.yaml

Fix: Add missing comma

---

.github/workflows/merge.yaml
.github/workflows/release.yaml
.github/workflows/triage.yaml

Enhancement: Reuse composite actions from `ergebnis/.github`

---

.github/workflows/integrate.yaml

Enhancement: Show colors when running `phpunit/phpunit` on GitHub Actions

---

README.md

Enhancement: Change call to action

---

.github/settings.yml
.github/workflows/integrate.yaml
Makefile

Enhancement: Run `composer audit` on GitHub Actions and in `Makefile`

---

.github/settings.yml
.github/workflows/integrate.yaml
.github/workflows/renew.yaml
composer.json
composer.lock

Fix: Drop support for PHP 7.4

---

.github/settings.yml
.github/workflows/integrate.yaml

Enhancement: Run tests on PHP 8.2

---

.github/settings.yml
.github/workflows/integrate.yaml
.github/workflows/renew.yaml
composer.json
composer.lock

Fix: Drop support for PHP 8.0

---

.github/SECURITY.md
README.md

💁‍♂️ For reference, see https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository.

Enhancement: Add `SECURITY.md`

---

README.md

Enhancement: Add PHP version support policy

---

.github/settings.yml
README.md
composer.json

Enhancement: Update `README.md`

---

README.md

Fix: Expand support to PHP versions with security support

---

.github/workflows/integrate.yaml
composer.json
composer.lock

Related to https://github.com/dependabot/dependabot-core/issues/5301#issuecomment-1850510422.

Fix: Configure and unset `platform` as needed

---

.github/CONTRIBUTING.md
.github/settings.yml
.github/workflows/integrate.yaml
.github/workflows/renew.yaml
Makefile
composer.json
composer.lock

Enhancement: Run backward-compatibility analysis with `roave/backward-compatibility-check`

---

.github/workflows/integrate.yaml
.github/workflows/renew.yaml
Makefile

Fix: Do not bother creating directories

---

.github/settings.yml
.github/workflows/integrate.yaml
composer.json
composer.lock

Enhancement: Add support for PHP 8.4
